# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=1000)),
                ('post_body', models.TextField()),
            ],
        ),
    ]
