# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='create_date',
        ),
    ]
