# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpost_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
