# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170528_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_title', models.CharField(max_length=50)),
                ('nav_desc', models.CharField(max_length=200)),
            ],
        ),
    ]
