# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='nav_location',
            field=models.CharField(default='#', max_length=1000),
            preserve_default=False,
        ),
    ]
