# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_navigation_nav_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='is_relative',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
