# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_navigation_is_relative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='is_relative',
            field=models.BooleanField(default=True),
        ),
    ]
