# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170603_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='nav_priority',
            field=models.SmallIntegerField(default=50),
        ),
    ]
